### ISSUE TITLE
Issue getting EOD datasets

### ISSUE THREAD

**Issue by csc5a2g** [CMEGroup/datamine_python#28]
Hi, 

I'm trying to get some EOD datasets but the process keeps dying with the following error:

_runfile('C:/Python/DatamineDownloader.py', wdir='C:/Python')
get_catalog: retrieving EOD, limit 100
get_catalog: 100-record limit reached
get_catalog: 125 records downloaded, 25 duplicates, 100 saved
downloading EOD data:   4%|▍         | 4/100 [00:00<00:23,  4.15it/s]File Handling Area, looking for Content-Disposition Header and Lacks a 'header'...
Expected a "filename" entry in the Content-Disposition header found:
  
See log file for further detail.
downloading EOD data:  67%|██████▋   | 67/100 [00:07<00:03, 10.91it/s]File Handling Area, looking for Content-Disposition Header and Lacks a 'header'...
Expected a "filename" entry in the Content-Disposition header found:
  
See log file for further detail.
downloading EOD data: 100%|██████████| 100/100 [00:11<00:00,  8.86it/s]
reading EOD data: 100%|██████████| 101/101 [00:02<00:00, 44.12it/s]
Traceback (most recent call last):

  File "C:\Python\DatamineDownloader.py", line 24, in <module>
    myDatamine.eod_load()

  File "C:\Anaconda3\lib\site-packages\datamine\io.py", line 364, in eod_load
    self.eod_DF = self.load_dataset('EOD', download=download)

  File "C:\Anaconda3\lib\site-packages\datamine\io.py", line 268, in load_dataset
    return Loader.by_name(dataset, dataset_args).load(path, limit=limit)

  File "C:\Anaconda3\lib\site-packages\datamine\loaders\base.py", line 121, in load
    'reading {} data'.format(self.dataset), max_workers)

  File "C:\Anaconda3\lib\site-packages\datamine\utils.py", line 34, in tqdm_execute_tasks
    return [f.result() for f in futures]

  File "C:\Anaconda3\lib\site-packages\datamine\utils.py", line 34, in <listcomp>
    return [f.result() for f in futures]

  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()

  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

downloading EOD data: 100%|##########| 100/100 [00:50<00:00,  1.98it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\DatamineDownloader.py", line 24, in <module>
    myDatamine.eod_load()
  File "C:\Anaconda3\lib\site-packages\datamine\io.py", line 364, in eod_load
    self.eod_DF = self.load_dataset('EOD', download=download)
  File "C:\Anaconda3\lib\site-packages\datamine\io.py", line 268, in load_dataset
    return Loader.by_name(dataset, dataset_args).load(path, limit=limit)
  File "C:\Anaconda3\lib\site-packages\datamine\loaders\base.py", line 121, in load
    'reading {} data'.format(self.dataset), max_workers)
  File "C:\Anaconda3\lib\site-packages\datamine\utils.py", line 31, in tqdm_execute_tasks
    futures = [executor.submit(fn, key) for key in keys]
  File "C:\Anaconda3\lib\site-packages\datamine\utils.py", line 31, in <listcomp>
    futures = [executor.submit(fn, key) for key in keys]
  File "C:\Anaconda3\lib\concurrent\futures\process.py", line 641, in submit
    self._start_queue_management_thread()
  File "C:\Anaconda3\lib\concurrent\futures\process.py", line 583, in _start_queue_management_thread
    self._adjust_process_count()
  File "C:\Anaconda3\lib\concurrent\futures\process.py", line 607, in _adjust_process_count
    p.start()
  File "C:\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
downloading EOD data:  97%|#########7| 97/100 [00:51<00:01,  1.63it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\DatamineDownloader.py", line 20, in <module>
    myDatamine.get_catalog("EOD", limit = 100)
  File "C:\Anaconda3\lib\site-packages\datamine\io.py", line 230, in get_catalog
    files = response['files']
KeyError: 'files'_

Any ideas how to correct this ?

**Comment by csc5a2g** [comment]
This was because I hadn't guarded the code correctly. Closing.
