### ISSUE TITLE
package installation failed

### ISSUE THREAD

**Issue by edgibba** [CMEGroup/datamine_python#30]
Good afternoon, I would like to ask for some help, I'm trying to install the Datamine package, but I've been having some errors, as attached,I'm using  python 3.10 :
---------------
----- Installing 'datamine' -----
Collecting datamine
  Using cached datamine-0.21.post2-py2.py3-none-any.whl (26 kB)
Collecting futures
  Using cached futures-3.0.5.tar.gz (25 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [27 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 14, in <module>
    File "C:\Python\Python310\lib\site-packages\setuptools\__init__.py", line 247, in <module>
      monkey.patch_all()
    File "C:\Python\Python310\lib\site-packages\setuptools\monkey.py", line 97, in patch_all
      patch_for_msvc_specialized_compiler()
    File "C:\Python\Python310\lib\site-packages\setuptools\monkey.py", line 157, in patch_for_msvc_specialized_compiler
      patch_func(*msvc14('_get_vc_env'))
    File "C:\Python\Python310\lib\site-packages\setuptools\monkey.py", line 147, in patch_params
      mod = import_module(mod_name)
    File "C:\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "C:\Python\Python310\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 20, in <module>
      import unittest.mock as mock
    File "C:\Python\Python310\lib\unittest\mock.py", line 26, in <module>
      import asyncio
    File "C:\Python\Python310\lib\asyncio\__init__.py", line 8, in <module>
      from .base_events import *
    File "C:\Python\Python310\lib\asyncio\base_events.py", line 18, in <module>
      import concurrent.futures
    File "C:\Users\eduar\AppData\Local\Temp\pip-install-9mxj3ucv\futures_210b3630192e4a0ca401b8b47bea3513\concurrent\futures\__init__.py", line 8, in <module>
      from concurrent.futures._base import (FIRST_COMPLETED,
    File "C:\Users\eduar\AppData\Local\Temp\pip-install-9mxj3ucv\futures_210b3630192e4a0ca401b8b47bea3513\concurrent\futures\_base.py", line 357
      raise type(self._exception), self._exception, self._traceback
                                 ^
  SyntaxError: invalid syntax
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
Encountered error while generating package metadata.
See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
----- Failed to install 'datamine' -----

**Comment by rgleavenworth** [comment]
This works with python 3.8 and is incompatible with Python version > 3.9. You'll have to setup a python environment that allows you to run python 3.8 or lower. You can do this in anaconda python with steps outlined here - https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by jeremytanjianle** [comment]
I notice that `futures` is added as a requirement. 

The pypi `futures` package is really a backport from python 2.
I quote directly from https://pypi.org/project/futures/:
> It does not work on Python 3 due to Python 2 syntax being used in the codebase. Python 3 users should not attempt to install it, since the package is already included in the standard library.

I'd like to report that I'm able to install and use the package smoothly after git cloning and removing this requirement.

I suggest reviewing the possible removal of this requirement.

**Comment by galexisz** [comment]
same error on 3.8
